NDefines.NMilitary.CORPS_COMMANDER_DIVISIONS_CAP = 24;
NDefines.NDiplomacy.MAX_TRUST_VALUE = 200;
NDefines.NDiplomacy.MIN_TRUST_VALUE = -200;
NDefines.NDiplomacy.MAX_OPINION_VALUEE = 200;
NDefines.NDiplomacy.MIN_OPINION_VALUE = -200;
NDefines.NBuildings.INFRASTRUCTURE_RESOURCE_BONUS = 0.0;
NDefines.NMilitary.MAX_DIVISION_SUPPORT_WIDTH = 2;